- CHANGELOG.md
- package.json
- src/client.ts
Handles the scenario where an open orders account is created outside of the SDK i.e. CPI.
> Set client open orders address on margin account callback.

- CHANGELOG.md
- src/idl/zeta.json
- src/types/zeta.ts
(Auto-generated from changes in https://github.com/zetamarkets/zeta-options/pull/415)
Liquidate size has been bumped to u64 in the zeta-options program, and the changes here are autogenerated based on that. Note that the typescript 'number' type is actually limited to ~u53 in practice 😊
> Autogenerated changes due to U64 liquidation size

- CHANGELOG.md
- src/idl/zeta.json
- src/program-types.ts
- src/types/zeta.ts
Goes hand-in-hand with the DEX PR https://github.com/zetamarkets/zeta-options/pull/429. From that description:
_Add new event LiquidationEvent, that gets emitted on every successful liquidate() instruction. We will use the indexers to enrich any liquidate() instructions with this additional information once it is in mainnet, as well as it just providing extra handy info for SDK users._
> Liquidation events

- CHANGELOG.md
- src/assets.ts
- src/client.ts
- src/constants.ts
- src/idl/zeta.json
- src/program-instructions.ts
- src/program-types.ts
- src/types.ts
- src/types/zeta.ts
- src/utils.ts
For multi-underlying support we want to know the asset of each margin and spread account. This adds it, and also forces any new accounts from here to pass in the asset.
> Add asset to marginaccount and spreadaccount

- CHANGELOG.md
- package.json
- src/client.ts
- src/events.ts
- src/program-types.ts
- src/subclient.ts
If we use `callback` in `subclient.load()`, only the last loaded subclient's callback will actually fire on trade/ordercomplete events because of some Anchor shenanigans.
This PR moves that subscription logic out to the client to fix this issue for 1 client. I'll raise an Anchor PR too.
> Bugfix client subscriptions

- CHANGELOG.md
- examples/basic/package.json
- package.json
- src/client.ts
- src/subclient.ts
- src/types.ts
Slight logic change to `cancelAllOrders()` and `cancelMultipleOrders()` to make them bundle multiasset cancels into a single tx.
- `cancelAllOrders()` now works primarily inside `Client`, only grabbing `cancelAllOrdersIxs()` from each `SubClient`.
- `cancelMultipleOrders()` is now purely inside `Client`. _**It now requires `Asset` in each of the CancelArgs[] instead of the function arguments, which is breaking if someone uses `cancelMultipleOrders()`**_.
- Same thing for the `NoError` equivalents of each function.
> Improve cancelAllOrders and cancelMultipleOrders

- CHANGELOG.md
- package.json
- src/constants.ts
Now that we can cancel orders across assets in one transaction, we've run into an edge case: If you try to cancel 4 orders across all 3 assets, all on different market indexes, you run over the tx size limit by 18 bytes. 
Therefore we just drop cancels_per_tx from 4 -> 3
> Drop cancels_per_tx down from 4 to 3

- CHANGELOG.md
- package.json
- src/client.ts
- src/idl/zeta.json
- src/program-instructions.ts
- src/types/zeta.ts
This PR adds a new instruction `cancelAllMarketOrders()` that will cancel all orders on a single market index in one go using Serum's `cpi::prune()`. The only other difference between `cancelAllMarketOrders()` and `cancelOrder()` is that here we don't provide a side + order ID. 
zeta-options PR: https://github.com/zetamarkets/zeta-options/pull/472
Fuze PR: https://github.com/zetamarkets/fuze/pull/28
> Add cancelAllMarketOrders

- package.json
- src/idl/zeta.json
- src/types/zeta.ts
Broke devnet due to IDL decoding, this fixes it. Mainnet is fine either way, having unused values in the enum doesn't cause any problems.
Already released as 0.16.19 yesterday.
> Fix Kind enum

- CHANGELOG.md
- examples/basic/package.json
- examples/cranking/package.json
- examples/liquidator-example/package.json
- examples/settlement-print/package.json
- examples/subscription/package.json
- package.json
- src/utils.ts
Bump solana-web3 library to fix a recursion issue we saw: https://github.com/solana-labs/solana/pull/28428
No issues in basic-example.ts with locally built SDK, and (backup mainnet) dex-webserver & dex-server with beta release of this PR. Released as 0.17.1-beta.3 if you want to try yourself 😊
> Bump to newest web3 lib

- CHANGELOG.md
- examples/basic/.env
- examples/basic/package.json
- examples/cranking/package.json
- examples/liquidator-example/.env
- examples/liquidator-example/package.json
- examples/settlement-print/.env
- examples/settlement-print/package.json
- examples/subscription/.env
- examples/subscription/package.json
- package.json
- src/client.ts
- src/subclient.ts
- src/utils.ts
Calculating the blockhash involves a roundtrip to the RPC, which takes time. SDK users can lower their latency by pre-caching the blockhash instead. This PR adds an optional `blockhash?: string` to `utils.processTransaction()`. It's only used in `client.placeOrder()` for now but we can theoretically add it to any transaction if there's appetite for it.
This PR also bumps the examples - I noticed that the SDK version and webserver URL were out of date 😊
> Add optional blockhash option to placeOrder() + bump examples

- CHANGELOG.md
- package.json
- src/utils.ts
Add an optional limit to the amount of events cranked at once in `utils.crankMarket()`
> Add crank limit

- CHANGELOG.md
- package.json
- src/client.ts
- src/idl/zeta.json
- src/program-instructions.ts
- src/program-types.ts
- src/subclient.ts
- src/types.ts
- src/types/zeta.ts
- src/utils.ts
Allow the user to specify a separate pubkey on behalf of which it performs actions - currently only placing and cancelling orders. We can add spread accounts and liquidations later because this is enough for now IMO.
> Delegated accounts

- CHANGELOG.md
- package.json
- src/exchange.ts
Store a map to grab zetagroup asset by pubkey without an RPC fetch or having to manually filter all zetaGroups
> Add handy function Exchange.zetaGroupPubkeyToAsset()

- CHANGELOG.md
- README.md
- package.json
- src/exchange.ts
- src/utils.ts
Allow the user to toggle on automatic priority fees, which polls getRecentPrioritizationFees() to determine a good fee using a median of the last 20 blocks of fees. Note that we pass in the perpsyncqueue and greeks accounts to the RPC function, as they're the most touched accounts during trading.
We also refactor the existing priority fee logic a bit, removing toggleUsePriorityFees to make things simpler. If you want manual fees, just set Exchange.updatePriorityFee() to be nonzero. If you want automatic fees, just call Exchange.toggleAutoPriorityFee().
> Use automatic priority fees

- CHANGELOG.md
- package.json
- src/exchange.ts
- src/types.ts
- src/utils.ts
Using `confirmTransaction()` with the new `BlockheightBasedTransactionConfirmationStrategy` provides a better UX in regards to transactions that time out or take a while to confirm. This PR changes that, and there's some extra syntax bits regarding the optional `blockhash` argument
> Use confirmTransaction with new args

- CHANGELOG.md
- package.json
- src/cross-client.ts
Support both `marginAccount` and `crossMarginAccount` in `forceCancelOrderByOrderId()`  and `forceCancelOrders()`
> Force cancel improvements for CrossMarginAccount

- CHANGELOG.md
- package.json
- src/client.ts
- src/constants.ts
- src/cross-client.ts
- src/risk-utils.ts
- src/risk.ts
- src/types.ts
- src/utils.ts
- getMaxTradeSize() - figures out the maximum size you can trade based on if you're closing or opening a position.
- getLiquidationPrice() - figures out at what price your position will get liquidated.
- Split uPnL calcs into estimateRealizedPnl() and calculateUnrealizedPnl()
- checkLiquidity() - finds the best price to execute an order at
> getMaxTradeSize(), getLiquidationPrice() and uPnL overhaul

- CHANGELOG.md
- package.json
- src/risk-utils.ts
- src/risk.ts
- src/types.ts
- src/utils.ts
Useful for FE to show a before/after for key account statistics.
These functions work by cloning the provided account and then using existing risk functions. Cloning is quite slow because it requires a deep clone on a big object, so I've provided the ability to provide your own cloned account as I assume we're going to be calling multiple of these at the same time.
To call all 5 functions on my machine it takes ~0.6ms if no executionInfo is provided, ~1.5ms if executionInfo is provided and an account is cloned beforehand (included in time measurement) and ~5ms if an account has to be cloned in each function.
> Post-trade calcs

- CHANGELOG.md
- package.json
- src/risk.ts
Caused some friction in FE so we don't want it to throw hard, instead just log out a warning and clamp to the min/max size.
> Clamp calculatePnl execution size instead of throwing

- CHANGELOG.md
- package.json
- src/constants.ts
- src/cross-client.ts
- src/exchange.ts
- src/idl/zeta.json
- src/program-instructions.ts
- src/program-types.ts
- src/risk.ts
- src/subclient.ts
- src/types.ts
- src/types/zeta.ts
- src/utils.ts
This PR implements trigger orders, which will be utilised for stop-loss/take-profit functionality. 
Functionality defaults to `FillOrKill` with trigger direction acting as a stop-loss/take-profit order (`INCREASING` if Ask, `DECREASING` if Bid), but you can use any order type and direction you wish to create more complicated things such as stop-limit orders.
Trigger price and order price are separate - as we don't have market order functionality in the program it's probably best to do `orderPrice = triggerPrice + slippage`, unless manually specified otherwise.
Trigger orders expire after `State.triggerOrderTimeoutSeconds`, and they can be deleted by an admin or the owner. They can also be edited by the owner (just the asset cannot be changed).
> Trigger orders (StopLoss/TakeProfit)

- CHANGELOG.md
- package.json
- src/exchange.ts
Useful for FE to scale prio fees as none/low/high, this PR adds an optional offset and multiplier to the auto fees
> Add auto prio fee offset and multiplier

- CHANGELOG.md
- package.json
- src/constants.ts
- src/cross-client.ts
Useful for FE when closing positions. Cancel all trigger orders for a given asset and then place one order on the same asset.
Tested locally in the following conditions:
- 55 trigger orders active -> completes in 6 txs
- 5 trigger orders active -> completes in 1 tx
- 0 trigger orders active -> completes in 1 tx
> Cancel all trigger orders + place order

- CHANGELOG.md
- package.json
- src/cross-client.ts
Small fix to stop undefined errors when the account is empty and we're checking trigger orders
> Better handling for empty account

- CHANGELOG.md
- package.json
- src/cross-client.ts
- src/exchange.ts
- src/market.ts
- src/serum/market.ts
- src/types.ts
@solana/web3.js doesn't support different encodings so I made a fork: https://github.com/zetamarkets/zeta-solana-web3.js. It essentially just adds some code into connection.ts to seamlessly allow both base64 and base64+zstd encodings.
This PR allows for the use of a Connection object from that fork, and defaults everything to using `base64+zstd` for the encoding. CPU usage is minimally increased but network usage is 5-10x lower.
> ZSTD compression for RPC websocket connections 

- CHANGELOG.md
- package.json
- src/cross-client.ts
- src/exchange.ts
- src/market.ts
- src/serum/scripts/market-gen.ts
- src/subclient.ts
- src/types.ts
- src/utils.ts
Optionally provide a buffer for when orders are not shown due to TIF. This is useful for slow internet connections on FE because it doesn't have to be exactly precise, and we'd prefer a consistent orderbook that doesn't cut out.
> Add new TIF buffer option

- CHANGELOG.md
- package.json
- src/exchange.ts
- src/utils.ts
Saw some errors like `The number 262.5 cannot be converted to a BigInt because it is not an integer` because we had decimal prio fees. This PR adds rounding to both the auto fee we fetch and also the fee we actually send, in case someone puts a decimal fee manually.
> Round priority fees

- CHANGELOG.md
- package.json
- src/cross-client.ts
- src/types.ts
Now that we're adding LIMIT order type for trigger orders, we should make the orderType param mandatory too 😊
> Make order type a required arg for trigger orders

- CHANGELOG.md
- package.json
- src/risk-utils.ts
- src/risk.ts
- Add fake trade functionality to `getEstimatedLiquidationPrice` so that FE can use it for order entry calcs
- Remove old functions `getLiquidationPrice` and `calculateLiquidationPrice`
> Reformat liquidation utils

- package.json
- src/idl/zeta.json
- src/types/zeta.ts
Remove the requirement for authority to be a signer, allowing CPI calls to be made more easily 😊
> Permissionless account creation

- CHANGELOG.md
- package.json
- src/risk.ts
Useful for an edge case in FE, an optional value to use the original equity for getLeverage() instead of the new one from the trade
> Override equity param in leverage util

- CHANGELOG.md
- package.json
- src/risk.ts
Setting maxLeverage allowed an unintended override to the trade size buffer if you had open orders, just add a Math.min() to patch this
> Bugfix getMaxTradeSize with leverage option

- CHANGELOG.md
- package.json
- src/risk-utils.ts
- src/risk.ts
- src/utils.ts
- Fix getMaxTradeSize() to correctly use uPnL
- Add optional `useExecutionInfoPrice` to `getLeverage`, allowing an override of the mark price
> Add mark price override in getLeverage

- CHANGELOG.md
- package.json
- src/assets.ts
- src/risk-utils.ts
- src/subexchange.ts
A bundle of a few small fixes:
- Fix anchor.BN truncation in risk calcs: small accounts will truncate uPnL to 0, causing accuracy issues with trade size and liq price calcs
- Replace throw with an undefined return for invalid asset: throwing is a bit too aggressive, and caused some issues in FE
- Add check for Exchange.isInitialized when refreshing markets: if loading is super slow then the .isHalted() check can cause syntax errors because Exchange.state is undefined
> Fix anchor.bn truncation, improve invalid asset behaviour and improve market refresh robustness

- CHANGELOG.md
- package.json
- src/utils.ts
Cranks struggled because they had to send hundreds of txs every time, mostly for empty accounts. Filter the accounts to only send txs we need, drastically reducing load (eg. thousands of accounts down to 50 for SOL)
> Only burn tokens for openOrdersAccounts that have nonzero tokens

- CHANGELOG.md
- package.json
- src/risk.ts
Added as a safety, but it's actually wrong and causing bad slider behaviour on FE. It isn't really necessary so I'm just removing it.
> Remove maxLeverage clamp in getMaxTradeSize

- CHANGELOG.md
- package.json
- src/constants.ts
- src/exchange.ts
- src/utils.ts
Improve auto prio fees:
- Change calc to use max instead of median (toggleable)
- Significantly increase default upper limit
Example fees:
> Better prio fees

- CHANGELOG.md
- package.json
- src/cross-client.ts
We're throwing too freely, instead just log a warning and use the utils pubkey which will be created later anyway
> Remove throw if no open orders account

- CHANGELOG.md
- package.json
- src/utils.ts
`.all()` was failing a lot now that we have ~40k accounts, so instead just grab a random subset of accounts to burn tokens for
> Refactor settleAndBurnVaultTokens

- CHANGELOG.md
- package.json
- src/utils.ts
Fixes issue when changing referral ID when you already have one that's <6 chars
> Trim trailing \0s on referral IDs

- CHANGELOG.md
- package.json
- src/constants.ts
anchor deserialisation assumes that enums are in order, so this breaks :(
> Fix withdrawonly enum

- CHANGELOG.md
- package.json
- src/cross-client.ts
add the try and catch to ignore Error: Invalid account discriminator when closing the cross margin account and account manager.
> fix 'Invalid account discriminator' error when close account
