zetamarkets/sdk

README.md
examples/basic/package.json

Fix package.json example and README error.

---

package-lock.json
src/client.ts
src/types.ts

* Multiple cancel method which takes in an array of cancel arg objects
* Anything over 4 cancels will be split into multiple txs

Multiple cancels

---

CHANGELOG.md
src/client.ts
src/exchange.ts
src/idl/zeta.json
src/program-instructions.ts
src/program-types.ts
src/utils.ts

associated sdk changes for PR https://github.com/zetamarkets/zeta-options/pull/322

Platform fees

---

CHANGELOG.md
src/exchange.ts
src/idl/zeta.json
src/program-instructions.ts
src/program-types.ts
src/risk.ts
src/types.ts

Update margin requirements for short put.

---

CHANGELOG.md
src/exchange.ts
src/idl/zeta.json
src/network.ts
src/program-instructions.ts
src/utils.ts

Mostly for hardware wallet support.

Add `UpdateAdmin`.

---

.npmignore
CHANGELOG.md
package.json
src/errors.ts
src/index.ts
src/utils.ts

Add basic native error handling.
- Zero SOL
- Insufficient SOL
- Transaction timeout
- Blockhash error

Add native error handling

---

CHANGELOG.md
src/idl/zeta.json
src/program-types.ts
src/types/zeta.ts

Corresponding SDK update for this PR: https://github.com/zetamarkets/zeta-options/pull/428

Add isTaker bool to PlaceOrderEvent

---

CHANGELOG.md
package.json

We see `TypeError: fields must be array of Layout instances` in the integration tests. This fixes it.

Fix builds

---

CHANGELOG.md
src/idl/zeta.json
src/program-types.ts
src/types/zeta.ts

This is a breaking change, so we'll hold off on it until we have other breaking changes to go out :)

Revert isTaker (for now)

---

CHANGELOG.md
src/events.ts
src/idl/zeta.json
src/program-types.ts
src/subclient.ts
src/types.ts
src/types/zeta.ts

Mostly autogenerated PR from https://github.com/zetamarkets/zeta-options/pull/453/. Bigger description is available over in that PR :)

Add OrderCompleteEvent

---

CHANGELOG.md
package.json
src/client.ts
src/subclient.ts

Just some little things ahead of 0.18.0:
1. Add a check to `createPlacePerpOrderInstruction` to make sure the user has an open orders account.
2. Improve `cancelAllOrders()` for multiasset

Small perp improvements

---

CHANGELOG.md
src/assets.ts
src/idl/zeta.json
src/subexchange.ts
src/types/zeta.ts
src/utils.ts

A few small changes from the corresponding main DEX PR: https://github.com/zetamarkets/zeta-options/pull/481

Fixing integration tests and perp halt/settlement

---

CHANGELOG.md
package.json
src/subclient.ts

Fixes bug where perp orders can't be edited on FE. Released as 0.19.3-beta.0 and tested by @wheeeliam

Add perp functionality to cancel+place functions

---

CHANGELOG.md
examples/basic/basic-example.ts
examples/basic/package.json
examples/cranking/cranking-example.ts
examples/cranking/package.json
examples/liquidator-example/package.json
examples/liquidator-example/src/liquidator.ts
examples/settlement-print/package.json
examples/settlement-print/settlement-print.ts
examples/subscription/package.json
examples/subscription/subscription.ts
examples/versioned-txes/package.json
examples/versioned-txes/versioned-txes.ts
package.json
src/assets.ts
src/client.ts
src/constants.ts
src/exchange.ts
src/idl/zeta.json
src/market.ts
src/program-instructions.ts
src/serum-market-store.ts
src/serum/market.ts
src/subclient.ts
src/subexchange.ts
src/types.ts
src/types/zeta.ts
src/utils.ts

Optimise Exchange loading

---

CHANGELOG.md
package.json
src/utils.ts

Add `roundingFactor` to `convertDecimalToNativeInteger`, defaults to `constants.TICK_SIZE`

Add roundingFactor to util function

---

CHANGELOG.md
package.json
src/subclient.ts
src/types.ts

Add extra data on the USER callback to tell where it came from

Add user callback type

---

CHANGELOG.md
package.json

Just some housekeeping - wasn't added in the actual PR 😊

Package and changelog for 0.26.4

---

CHANGELOG.md
package.json
src/subclient.ts
src/types.ts

Quick one to add asset to the locally stored position, removes a bit of code complexity when grabbing all positions

Add asset to SDK Position

---

CHANGELOG.md
package.json
src/risk.ts

Bit of cleanup in the risk calculator following a bug report

Fix risk calcs

---

CHANGELOG.md
package.json
src/events.ts
src/exchange.ts

Subscribe to pricing changes rather than polling.

Better pricing subscription

---

CHANGELOG.md
package.json
src/exchange.ts

Add an optional upper limit for auto fees so it doesn't blow up and rug you without notice, defaulting to the default fee (1000).

Auto fee upper limit

---

CHANGELOG.md
src/exchange.ts
src/risk-utils.ts
src/risk.ts
src/subexchange.ts

- Use Pricing.mark_prices directly instead of relying on update fn

Clean up some risk calculations

---

CHANGELOG.md
package.json
src/risk-utils.ts
src/risk.ts
src/utils.ts

Improve getMaxTradeSize() by using a binary search approach to simulate the best state after it executes. Also improve comments on functions to include descriptions on precision and whether things are signed/unsigned.

Better estimated PnL calc

---

CHANGELOG.md
package.json
src/risk-utils.ts

Quick one-liner - need to absolute value the size

Bugfix posttrade

---

CHANGELOG.md
package.json
src/risk.ts

Quick one to make life easier for FE 😊

Risk utils return 0 if balance is 0

---

CHANGELOG.md
package.json
src/cross-client.ts
src/subclient.ts
src/types.ts

- Fix typo in comments for throttle param
- Default reduceOnly to true in default trigger orders params

Default reduceOnly to true in trigger orders

---

CHANGELOG.md
package.json
src/cross-client.ts
src/events.ts
src/exchange.ts
src/market.ts
src/program-instructions.ts
src/risk-utils.ts
src/serum/market.ts
src/serum/scripts/market-gen.ts
src/subclient.ts
src/subexchange.ts
src/types.ts
src/utils.ts

- Subscribe to orderbook changes instead of polling
- Delete a bunch of old options stuff from the market files

Subscribe to orderbooks and clean up some old code

---

package.json
src/exchange.ts
src/risk.ts

Fixes two errors with sentry
1) `subExchange` map missing value for a certain key sometimes
2) `MarginRequirement` can be `undefined` in addition to `null`

Fix: Sentry errors

---

CHANGELOG.md
package.json
src/risk.ts

Quick one to catch some FE errors nicely

Return undefined from getMaxTradeSize if price is 0

---

CHANGELOG.md
package.json
src/exchange.ts
src/risk.ts
src/utils.ts

- Add maxRetries option to transactions, 0 is preferred for cranking to not spam on errors
- Split burn util up further to prevent it from eating RAM

Robustness improvements

---

CHANGELOG.md
package.json
src/exchange.ts

Extra utils to explicitly set values that get toggled

new set utils

---

CHANGELOG.md
package.json
src/utils.ts

Confirmed by Triton that this is correct

Remove 151 from blockheight check

---

CHANGELOG.md
package.json
src/cross-client.ts

We run out of CU with the default 200k cap. We could simulate the tx and decide but had some trouble with it in the other PR so this is the quick option.

Add extra CU to some ixs

---

CHANGELOG.md
package.json
src/constants.ts

Needed to fix program repo integration tests. Also adds changelogs from TRUMP asset.

Fix integration tests
